## Homework 1

Please import the following packages.

In [2]:
import numpy as np
import scipy.sparse

Please download `memory.py` from Resources/Homework/Homework01 on NYU Classes. Save it to the same directory as the Jupyter notebook. Please import the following package.

In [3]:
import memory

### Loops

**_How to go through the entries of an array top to bottom/left to right?_**

1. Given an array `inputArray`, write a `for` loop that flattens it to `outputArray`. For example, `inputArray = np.array([[1,2], [3,4]])`
would yield `np.array([1,2,3,4])` for `outputArray`.

In [4]:
inputArray = np.array([[1,2],[3,4]])
print(inputArray)
outputArray = inputArray.flatten()
print(outputArray)

outputArray = []
for row in inputArray: 
    for elem in row: 
        outputArray.append(elem)

outputArray = np.array(outputArray)
        
print(outputArray)
print(type(outputArray))

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
# List Comprension
output_array = np.array([
    elem
    for row in inputArray
    for elem in row
])

In [8]:
output_array

array([1, 2, 3, 4])

2. Given a jagged array `inputArray`, write a `for` loop that flattens it to `outputArray`. For example, `inputArray = np.array([[1,2,3], [4]])`
would yield `np.array([1,2,3,4])` for `outputArray`.

In [9]:
inputArray = np.array([[1,2,3], [4]])
print(inputArray)
print(type(inputArray))
outputArray = np.ravel(inputArray.flatten())
print(outputArray)
outputArray = inputArray.reshape(-1)
print(outputArray)

outputArray = []
for i in inputArray: 
    for j in i: 
        outputArray.append(j)
        #np.asarray(outputArray)
outputArray = np.array(outputArray)

print(outputArray)
outputArray
print(type(outputArray))

[list([1, 2, 3]) list([4])]
<class 'numpy.ndarray'>
[list([1, 2, 3]) list([4])]
[list([1, 2, 3]) list([4])]
[1 2 3 4]
<class 'numpy.ndarray'>


### Packages
**_How to import and use packages?_**

3. Create an array `A` from the list 

`[[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]]`

Use `memory.getsizeof` to determine how much space `A` takes up in memory.

In [36]:
A = [[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]]
print(A)
print(type(A))

A = np.asarray(A)
print(A)
print(type(A))

memory.getsizeof(A)

[[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]]
<class 'list'>
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
<class 'numpy.ndarray'>


144

4. Use `scipy.sparse.csr_matrix` to covert `A` into `S`. Use `memory.getsizeof` to determine how much space `S` takes up in memory.

In [37]:
S = scipy.sparse.csr_matrix(A)
print(S)

memory.getsizeof(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


76

5. What accounts for the difference? Try calling `print` on `S`.

In [33]:
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [ ]:
# The difference in storage is caused by the space saved when using a sparse matrix vs a dense matrix. (https://machinelearningmastery.com/sparse-matrices-for-machine-learning/). 
# Sparse matrices are comprised mostly of 0 values. We are not saving the 0's in a sparse matrix. 