## Homework 2

Please import the following package.

In [66]:
import numpy as np

### Loops

**_How to work with multiple indices?_**

<ol>
    <li> 
        
Use the code from Homework 1 Question 1 to write a function `flatten` that takes as input an array with shape `(r,c)` and outputs an array with shape `(rc,)`.  For example, input `np.array([[1,2], [3,4]])` would yield output `np.array([1,2,3,4])`. Note that the array has two indices. The indices indicate the row and column. We flatten the array by going across the columns in each row. 
    </li>

In [67]:
# Implement this
outputArray = []

def flatten(arr):
    for row in arr:
        for elem in row:
            outputArray.append(elem)
    return(outputArray)
    
#     raise NotImplementedError()


In [68]:
#arr =[[1,2], [3,4]]
arr = np.array([[1,2], [3,4]])
flatten(arr)

[1, 2, 3, 4]

In [69]:
arr.dtype

dtype('int64')

<ol start=2>
<img src="diagram.png" alt="drawing" width="200" style="float:right"/>

<br>
<br>


<li> Modify the function from Question 1. 
 <ul> 
     <li> 
         
Add a parameter called `major`. 
     </li> 
 <li> 
     
Make the default value of `major` be `"row"`
 </li>
 <li> Rewrite the loop so 
      <ul> 
          <li>
              
If `major` is `"row"`, then the array is flattened in row major order
          </li>
      <li> 
      
If `major` is `"column"`, then the array is flattened in column major order 
      </li>
     </ul>
</li>
</ul>
</li>

</ol>

In [70]:
# Implement this, including modifying arguments

def flatten_v2(arr, major="row"):
    outputArray = []
    if major == "row":
        for i in len(arr):
            outputArray.append(i)
                for j in i:
                    outputArray.append(i)
                
    if major == "column": 
        for j in arr: 
            for i in j: 
                outputArray.append(j)
    return outputArray



IndentationError: unexpected indent (<ipython-input-70-64b2cc422584>, line 11)

In [92]:
arr = np.array([[1,2,3],[4,5,6]])

def flatten_v2(arr, major="row"): 
    outputArray = []
    row, col = arr.shape
    if major == "row":
        for i in range(row): 
            for j in range(col): 
                outputArray.append(arr[i][j])
    if major == "column": 
        for i in range(col): 
            for j in range(row): 
                outputArray.append(arr[j][i])
    return(outputArray)

print(flatten_v2(arr))
print(flatten_v2(arr, "column"))

[1, 2, 3, 4, 5, 6]
[1, 4, 2, 5, 3, 6]


In [57]:
arr = np.array([[1,2, 3], [3,4]])
arr
# len(arr)
# len(arr[:1])
len(arr[1:])

1

In [45]:
arr = np.array([[1,2], [3,4]])
major = "row"

flatten_v2(arr, major)



[array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4]),
 array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4])]

In [47]:
arr = [[1,2], [3,4]]
major = "row"

flatten_v2(arr, major)


[array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4]),
 array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4]),
 array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4]),
 [1, 2],
 [1, 2],
 [3, 4],
 [3, 4]]

In [48]:
arr = np.array([[1,2], [3,4]])
major = "column"
flatten_v2(arr, major)

[array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4]),
 array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4]),
 array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4]),
 [1, 2],
 [1, 2],
 [3, 4],
 [3, 4],
 array([1, 2]),
 array([1, 2]),
 array([3, 4]),
 array([3, 4])]

In [50]:
#Alternatively, using numpy
c = np.array([[1,2,3],
              [4,6,7]], order='C')

f = np.array([[1,2,3],
              [4,6,7]], order='F')
#https://en.wikipedia.org/wiki/Row-_and_column-major_order 

<ol start=3>

<li> 
    
Modify the function from Question 1 to allow for more than two indices. For example, if the input is an array with shape `(r,c,h)` then the output is an array with shape `(rch,)`. So input `np.array([ [[1,2], [3,4]], [[5,6], [7,8]] ])` which has shape `(2,2,2)` would yield output `np.array([1,2,3,4,5,6,7,8])` which has shape `(8,)`. You should approach the problem using recursion.  
</li>

</ol>

In [64]:
# Implement this
outputArray = []

def flatten_v3(arr):
#     raise NotImplementedError()
    if type(arr) == np.array: 
        outputArray = flatten_v3(arr)
    else: 
        outputArray.append([elem in row for row in arr])
    return(outputArray + flatten_v3(arr))

In [65]:
arr = np.array([[1,2], [3,4]])

flatten_v3(arr)

UnboundLocalError: local variable 'outputArray' referenced before assignment

### Storage

**_How to compress an array with lots of zeros_**

<ol>
<li>
Write a function called `dense_to_sparse` that inputs an array and outputs a dictionary with 
    <ul>
<li>
Keys as tuples containing `(row,column)` of all non-zero entries    
</li>
<li>
Values as the corresponding non-zero entries.
</li>
</ul>

The resulting entries should be in <i>row-major</i> order.

For example, if the input is `np.array([[1,0], [0,4]])` then the output is `{(0,0):1, (1,1):4}`       
</li>
</ol>
    

In [ ]:
# Implement this
def dense_to_sparse(arr):
    raise NotImplementedError()

<ol start=2>
<li>
    
Write an inverse function called `sparse_to_dense`
</li>
</ol>

In [ ]:
# Implement this
def sparse_to_dense(arr):
    raise NotImplementedError()