## Demo 1

### Variables

In [2]:
1+5

6

In [3]:
3 + 5 * 4

23

In [4]:
weight_kg = 60

In [6]:
aaaaa = 1

In [8]:
_ = 2
two_books = 5

In Python, variable names:

 * can include letters, digits, and underscores
 * cannot start with a digit
 * are case sensitive.

This means that, for example:

 * `weight0` is a valid variable name, whereas `0weight` is not
 * `weight` and `Weight` are different variables

### Types 

Python knows various types of data. Three common ones are:

 * integer numbers (`int`)
 * floating point numbers (`float`)
 * strings (`str`), and
 * bool (`bool`)

In [13]:
weight_kg = "weight in kilograms"

In [14]:
weight_kg = 60.0

### Using Variables

In [12]:
print(weight_kg)

60.0


In [15]:
print("weight in kgs", weight_kg)

weight in kgs 60.0


In [17]:
print("weight in kgs" + str(1))

weight in kgs1


### Importing Libraries

In [18]:
import numpy as np

The need for aliases

In [19]:
np.loadtxt?

In [20]:
data = np.loadtxt(fname='inflammation.csv', delimiter=',')

In [21]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [22]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [24]:
type(data)

numpy.ndarray

In [25]:
data.dtype

dtype('float64')

In [26]:
data.shape

(60, 40)

In [27]:
print('first value in data:', data[0, 0])

first value in data: 0.0


In [28]:
print('middle value in data:', data[30, 20])

middle value in data: 13.0


In [29]:
print('data:', data[30, 39])

data: 1.0


In [31]:
print('data:', data[30, -5])

data: 5.0


![](images/arrays.png)

### Slicing Data 

In [32]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [33]:
data[0:4, 0:10].shape

(4, 10)

In [ ]:
print(data[5:10, 0:10])

In [35]:
data[5:10, 0:10]

array([[0., 0., 1., 2., 2., 4., 2., 1., 6., 4.],
       [0., 0., 2., 2., 4., 2., 2., 5., 5., 8.],
       [0., 0., 1., 2., 3., 1., 2., 3., 5., 3.],
       [0., 0., 0., 3., 1., 5., 6., 5., 5., 8.],
       [0., 1., 1., 2., 1., 3., 5., 3., 5., 8.]])

In [36]:
doubledata = data * 2.0

In [37]:
print('original:')
print(data[:3, 36:])
print('doubledata:')
print(doubledata[:3, 36:])

original:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
doubledata:
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


In [40]:
print(np.mean(data))

6.14875


### Functions

In [41]:
import time
print(time.ctime())

Mon Sep  9 19:33:31 2019


In [42]:
maxval = np.max(data)

print('maximum inflammation:', maxval)

# comments

maximum inflammation: 20.0


In [49]:
# [patient, days]
# [row, column]
# [60, 40]
# [0, 1]
np.max(data, axis=1)

array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])

In [50]:
data.shape

(60, 40)

In [52]:
np.max(data, axis=1).shape

(60,)

In [46]:
np.max(data, axis=1)

array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])

![](images/max.PNG)