# Getting comfortable with Python 

Let's do all the types! (well, not *all* of them)

In [1]:
type(1)

int

In [2]:
type(1.5)

float

In [3]:
type("hello")

str

In [4]:
type("h")

str

In [5]:
type(True)

bool

In [6]:
print("Hello")

Hello


In [7]:
type(print)

builtin_function_or_method

In [8]:
type(print("Hello"))

Hello


NoneType

In [9]:
type(None)

NoneType

In [10]:
type(type(1))

type

In [11]:
type(type)

type

# Importing NumPy

It is customary to import NumPy as `np`:

In [12]:
import numpy as np

As you will cover in homework one, the `np.array` is the key data structure in numpy for dense arrays of data.

(More precisely, the type is `np.ndarray`, but we use `np.array` to construct them.)

NumPy `array`s have 2 main properties you need to keep in mind:

1. Shape
2. Data type (or `dtype`) of the data they contain

In particular, a NumPy `array` can only contain data of a single type (more nuance on this later).

# Creating Arrays

<span style="color:red; font-weight: bold;">What is `x1`'s `shape` and `dtype`?</span>

In [13]:
x1 = np.array([
    [1., 2.], 
    [3., 4.],
])

In [14]:
x1

array([[1., 2.],
       [3., 4.]])

In [15]:
x1.shape

(2, 2)

In [16]:
type(x1)

numpy.ndarray

<span style="color:red; font-weight: bold;">What is `x2`'s `shape` and `dtype`?</span>

In [17]:
x2 = np.array([x for x in range(5)])

In [18]:
x2

array([0, 1, 2, 3, 4])

In [19]:
x2.shape

(5,)

In [20]:
x2.dtype

dtype('int64')

In [21]:
type(x2)

numpy.ndarray

Array's don't have to contain numbers:

<span style="color:red; font-weight: bold;">What is `x3`'s `shape` and `dtype`?</span>

In [22]:
x3 = np.array([
    ["A", "matrix"], 
    ["of", "words."]
])

In [23]:
x3

array([['A', 'matrix'],
       ['of', 'words.']], dtype='<U6')

In [24]:
x3.shape

(2, 2)

In [26]:
x3.dtype

dtype('<U6')

In [27]:
type(x3)

numpy.ndarray

## Making Arrays of Zeros

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## Making Arrays of Ones

In [29]:
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Making an 'identity matrix'

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
x = np.eye(4)

In [32]:
x.astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
int, np.int64

(int, numpy.int64)

## Getting Diagonals

Confusingly, `np.diag` serves two purposes:

In [34]:
np.arange(4)

array([0, 1, 2, 3])

In [35]:
np.diag(np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [36]:
np.diag(np.diag(np.arange(4)))

array([0, 1, 2, 3])

## Making Arrays from ranges:

The `np.arange(start, stop, step)` function is like the python `range` function.

In [37]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [38]:
np.arange(0, 10, 0.7)

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9, 5.6, 6.3, 7. , 7.7, 8.4,
       9.1, 9.8])

In [39]:
np.arange(10, 0, -0.7)

array([10. ,  9.3,  8.6,  7.9,  7.2,  6.5,  5.8,  5.1,  4.4,  3.7,  3. ,
        2.3,  1.6,  0.9,  0.2])

In [43]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

You can make a range of other types as well:

## Interpolating numbers 

The `linspace(start,end,num)` function generates `num` numbers evenly spaced between the `start` and `end`.

In [44]:
np.linspace(0, 100, 7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

Learn more about working with [datetime objects](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#).


# Properties of Arrays

## Shape

Arrays have a shape which corresponds to the number of rows, columns, fibers, ...

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
arr.shape

[[1. 2. 3.]
 [4. 5. 6.]]


(2, 3)

## Type

Arrays have a type which corresponds to the type of data they contain

In [46]:
arr.dtype

dtype('float64')

In [47]:
np.arange(1, 5).dtype

dtype('int64')

In [48]:
(np.array([True, False])).dtype

dtype('bool')

In [49]:
np.array(["Hello", "Worlddddd!"]).dtype

dtype('<U10')

What does `<U6` mean?

- `<` Little Endian
- `U` Unicode
- `6` length of longest string

#### and we can change the type of an array:

In [50]:
np.array([1, 2, 3]).astype(float)

array([1., 2., 3.])

In [51]:
np.array(["1", "2", "3"]).astype(int)

array([1, 2, 3])

Learn more about numpy [array types](https://docs.scipy.org/doc/numpy/user/basics.types.html)


# Jagged Arrays

Is the following valid?

```python
arr = np.array([[1, 2, 3], [4, 5], [6]])
```

In [52]:
arr = np.array([
    [1, 2, 3], 
    [4, 5], 
    [6],
])

In [53]:
arr.shape

(3,)

In [54]:
arr.dtype

dtype('O')

In [55]:
arr

array([list([1, 2, 3]), list([4, 5]), list([6])], dtype=object)

In [56]:
arr = np.array([
    [1, 2, 3], 
    "str", 
    np.array(0),
])

In [57]:
arr

array([list([1, 2, 3]), 'str', array(0)], dtype=object)

What happened? 

In [59]:
# We got an array with mixed datatypes, containing a list, a string, and another array.

In [60]:
type(arr)

numpy.ndarray

### Issues with Jagged Arrays

 <img src="http://csharpcorner.mindcrackerinc.netdna-cdn.com/UploadFile/955025/C-Sharp-interview-question-part2/Images/jagged%20array.png">

### Jagged arrays can be problematic:

1. Difficult to index (extract columns).
```python
arr[0,1] 
 > Error
arr[0][1] 
 > 2
```
1. Not as efficiently represented in contiguous memory.

# Reshaping

Often you will need to reshape matrices.  Suppose you have the following array:

In [71]:
arr = np.arange(1, 13)

<span style="color:red; font-weight:bold;">What will the following produce:</span>

```python
np.arange(1, 13).reshape(4,3)
```

**Option A:**

```python
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
```

**Option B:**

```python
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])
```

**Solution**

In [72]:
np.arange(1, 13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Flattening Matrix

Flattening a matrix (higher dimensional array) produces a one dimensional array.

In [73]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
arr.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
#

In [77]:
arr.reshape(1, 1, 1, 1, -1).shape

(1, 1, 1, 1, 12)

## Checking equality

In [78]:
is_equal = (arr.flatten() == arr.reshape(12))

In [79]:
np.all(arr.flatten() == arr.reshape(12))

True

In [80]:
(arr.flatten() == arr.reshape(12)).all()

True

# Review

We covered a lot of concepts, but make sure you know what each of these do:

* `type`
* `np.array`
* `np.arange`
* `np.linspace`

Where `x` is an `ndarray`:

* `x.dtype`
* `x.shape`
* `x.flatten`
* `x.reshape`

<span style="color:red; font-weight:bold;">As an exercise for yourself, write a one-sentence description of what each one does. This will help you retain information better!</span>