# Importing Numpy

It is customary to import Numpy as `np`:

In [2]:
import numpy as np

As you learned in homework one the `np.array` is the key data structure in numpy for dense arrays of data.

# Creating Arrays

In [3]:
np.array([[1.,2.], [3.,4.]])

array([[ 1.,  2.],
       [ 3.,  4.]])

In [4]:
np.array([x for x in range(5)])

array([0, 1, 2, 3, 4])

Array's don't have to contain numbers:

In [5]:
np.array([["A", "matrix"], ["of", "words."]])

array([['A', 'matrix'],
       ['of', 'words.']], 
      dtype='<U6')

## Making Arrays of Zeros

In [6]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

## Making Arrays of Ones

In [7]:
np.ones([3,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [8]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Making Arrays from ranges:

The `np.arange(start, stop, step)` function is like the python `range` function.

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

You can make a range of other types as well:

## Interpolating numbers 

The `linspace(start,end,num)` function generates `num` numbers evenly spaced between the `start` and `end`.

In [11]:
np.linspace(0, 5, 10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

Learn more about working with [datetime objects](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#).


# Properties of Arrays

## Shape

Arrays have a shape which corresponds to the number of rows, columns, fibers, ...

In [15]:
A = np.array([[1., 2., 3.], [4., 5., 6.]])
print(A)
A.shape

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


(2, 3)

## Type

Arrays have a type which corresponds to the type of data they contain

In [16]:
A.dtype

dtype('float64')

In [17]:
np.arange(1,5).dtype

dtype('int64')

In [18]:
(np.array([True, False])).dtype

dtype('bool')

In [19]:
np.array(["Hello", "Worlddddd!"]).dtype

dtype('<U10')

What does `<U6` mean?

- `<` Little Endian
- `U` Unicode
- `6` length of longest string

#### and we can change the type of an array:

In [20]:
np.array([1,2,3]).astype(float)

array([ 1.,  2.,  3.])

In [21]:
np.array(["1","2","3"]).astype(int)

array([1, 2, 3])

Learn more about numpy [array types](https://docs.scipy.org/doc/numpy/user/basics.types.html)


# Jagged Arrays

Is the following valid?

```python
A = np.array([[1, 2, 3], [4, 5], [6]])
```

In [24]:
A = np.array([[1, 2, 3], [4, 5], [6]])
A

array([[1, 2, 3], [4, 5], [6]], dtype=object)

What happened? 

In [25]:
A.shape

(3,)

In [26]:
print(A.dtype)

object


In [27]:
print(A[0])
print(A[1])
print(A[2])

[1, 2, 3]
[4, 5]
[6]


### Issues with Jagged Arrays

 <img src="http://csharpcorner.mindcrackerinc.netdna-cdn.com/UploadFile/955025/C-Sharp-interview-question-part2/Images/jagged%20array.png">

### Jagged arrays can be problematic:

1. Difficult to index (extract columns).
```python
A[0,1] 
 > Error
A[0][1] 
 > 2
```
1. Not as efficiently represented in contiguous memory.

# Reshaping

Often you will need to reshape matrices.  Suppose you have the following array:

In [28]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**What will the following produce:**

```python
np.arange(1,13).reshape(4,3)
```

**Option A:**

```python
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
```

**Option B:**

```python
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])
```

**Solution**

In [29]:
A = np.arange(1,13).reshape(4,3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Flattening Matrix

Flattening a matrix (higher dimensional array) produces a one dimensional array.

In [30]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])